### ISSUE TITLE
PA Review: Servers

### ISSUE THREAD

**Issue by AprilHGraves** [AprilHGraves/aA-DiscordClone#3]
#### Servers
- [x] Users can create servers
- [x] Server owners can change a server's name and photo
- [x] Server owners can destroy servers
#### Server Invites
- [x] Server owner can generate invite links
- [x] Accessing the instant invite component either fetches a previous link or creates a new one with 24 hours set as the duration.
- [x] New invite links can be customized by selecting a duration and max-use limit
- [x] Using an invite link increases its uses by 1
- [x] Server owner can view and destroy invite links  on the server settings page

#### Server Memberships
- [x] Users can use invite links to join servers via url or through the "join a server component"
- [x] Users can leave servers
- [x] Users can set a nickname to be shown on a server

### Backend
- [x] DB servers, server_invites, and server memberships tables
- [x] models with validations
- [x] controllers with appropriate CRUD

### Frontend
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation

**Comment by Carly-Schaaf** [comment]
Awesome job, April! This looks finished to me!
